main - Tweaky!

diff --git a/bin/git-cleanup-remote-gone-branches b/bin/git-cleanup-remote-gone-branches
--- a/bin/git-cleanup-remote-gone-branches
+++ b/bin/git-cleanup-remote-gone-branches
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# Check whether we are inside a Git repository
+if ! git rev-parse --git-dir > /dev/null 2>&1; then
+  echo "Error: Not inside a Git repository"
+  exit 1
+fi
+
 # Fetch updates from the remote and prune deleted branches
 git fetch -p
 
